[versions]
jackson = "2.18.1"

[libraries]
jackson-datatype-jsr310 = { group = "com.fasterxml.jackson.datatype", name = "jackson-datatype-jsr310", version.ref = "jackson"}
jackson-annotations = { group = "com.fasterxml.jackson.core", name = "jackson-annotations", version.ref = "jackson"}
jackson-databind = { group = "com.fasterxml.jackson.core", name = "jackson-databind", version.ref = "jackson"}
jackson-core = { group = "com.fasterxml.jackson.core", name = "jackson-core", version.ref = "jackson"}

janino = { group = "org.codehaus.janino", name = "janino", version = "3.1.6" }
apache-commons-lang3 = "org.apache.commons:commons-lang3:3.12.0"
keycloak-admin-client = "org.keycloak:keycloak-admin-client:24.0.4"
jakarta-ws-rs-api = "jakarta.ws.rs:jakarta.ws.rs-api:3.1.0"